<?php
require_once('header.php');

require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

//Fetch data from database
$rennfahrer_array = $database->selectAllRennfahrerin();
?>

<head>
    <title>Rennfahrer</title>
</head>

<body>
<br>
<h1>Rennfahrer</h1>

<!-- Add Rennfahrerin -->
<h2>Add Rennfahrer: </h2>
<form method="get" action="addRennfahrerin.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- teamid textbox -->
    <div>
        <label for="new_teamid">teamid:</label>
        <input id="new_teamid" name="teamid" type="number" maxlength="50">
    </div>
    <br>

    <!-- vorname textbox -->
    <div>
        <label for="new_vorname">vorname:</label>
        <input id="new_vorname" name="vorname" type="text" maxlength="50">
    </div>
    <br>

    <!-- nachname textbox -->
    <div>
        <label for="new_nachname">nachname:</label>
        <input id="new_nachname" name="nachname" type="text" maxlength="50">
    </div>
    <br>

    <!-- nationalitaet textbox -->
    <div>
        <label for="new_nationalitaet">nationalitaet:</label>
        <input id="new_nationalitaet" name="nationalitaet" type="text" maxlength="50">
    </div>
    <br>

    <!-- Datum textbox -->
    <div>
        <label for="new_gebdatum">gebdatum (yyyy/mm/dd):</label>
        <input id="new_gebdatum" name="gebdatum" type="text" maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Rennfahrer/in
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Rennfahrerin -->
<h2>Delete Rennfahrer: </h2>
<form method="get" action="deleteRennfahrerin.php">
    <!-- teamid textbox -->
    <div>
        <label for="del_teamid">TeamId:</label>
        <input id="del_teamid" name="teamid" type="number" min="0">
    </div>
    <br>
    <!-- vorname textbox -->
    <div>
        <label for="del_vorname">Vorname:</label>
        <input id="del_vorname" name="vorname" type="text">
    </div>
    <br>
    <!-- nachname textbox -->
    <div>
        <label for="del_nachname">Nachname:</label>
        <input id="del_nachname" name="nachname" type="text">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Rennfahrer/in
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Rennfahrer Search:</h2>
<form method="get" action="searchRennfahrer.php">
    <!-- teamid textbox:-->
    <div>
        <label for="teamid">Teamid:</label>
        <input id="teamid" name="teamid" type="number">
    </div>
    <br>
    <!-- vorname textbox:-->
    <div>
        <label for="vorname">Vorname:</label>
        <input id="vorname" name="vorname" type="text" value='' min="0">
    </div>
    <br>
    <!-- nachname textbox:-->
    <div>
        <label for="nachname">Nachname:</label>
        <input id="nachname" name="nachname" type="text" value='' min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>
<a href="allRennfahrerin.php"> See all Rennfahrer </a>


</body>
</html>