<?php
require_once('header.php');

require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

//Fetch data from database
$rennfahrer_array = $database->selectAllWagen();
?>

<head>
    <title>Wagen</title>
</head>

<body>
<br>
<h1>Wagen</h1>

<!-- Add Wagen -->
<h2>Add Wagen: </h2>
<form method="get" action="addWagen.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- teamid textbox -->
    <div>
        <label for="new_teamid">Teamid:</label>
        <input id="new_teamid" name="teamid" type="number" maxlength="50">
    </div>
    <br>

    <!-- vorname textbox -->
    <div>
        <label for="new_vorname">Vorname:</label>
        <input id="new_vorname" name="vorname" type="text" maxlength="50">
    </div>
    <br>

    <!-- nachname textbox -->
    <div>
        <label for="new_nachname">Nachname:</label>
        <input id="new_nachname" name="nachname" type="text" maxlength="50">
    </div>
    <br>

    <!-- modell textbox -->
    <div>
        <label for="new_modell">Modell:</label>
        <input id="new_modell" name="modell" type="text" maxlength="100">
    </div>
    <br>

    <!-- jahr textbox -->
    <div>
        <label for="new_jahr">Jahr:</label>
        <input id="new_jahr" name="jahr" type="number" maxlength="20">
    </div>
    <br>

    <!-- leistung textbox -->
    <div>
        <label for="new_leistung">Leistung in kW:</label>
        <input id="new_leistung" name="leistung" type="number" maxlength="20">
    </div>
    <br>

    <!-- gewicht textbox -->
    <div>
        <label for="new_gewicht">Gewicht in kg:</label>
        <input id="new_gewicht" name="gewicht" type="number" maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Wagen
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form by autoId-->
<h2>Wagen Search by autoId:</h2>
<form method="get" action="searchWagen.php">
    <!-- autoId textbox:-->
    <div>
        <label for="autoid">autoId:</label>
        <input id="autoid" name="autoid" type="number">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>
<a href="allWagen.php"> See all Wagen </a>


</body>
</html>