<?php
require_once('header.php');
//include DatabaseHelper.php file
require_once('DatabaseHelper.php');

//instantiate DatabaseHelper class
$database = new DatabaseHelper();
//Grab variables from POST request

$teamid=$_GET['teamid'];
$vorname=$_GET['vorname'];
$nachname=$_GET['nachname'];
$suchen=$database->searchRennfahrerin($teamid, $vorname, $nachname);

$suchen=array_shift($suchen);

if (count($suchen) == 0 ){
    echo "Error can't find Rennfahrer with vorname: '{$vorname}', last name '{$nachname}' from team {$teamid}.";
    die();
}
?>

    <h2>Edit Rennfahrer: </h2>
    <form method="get" action="addupdateRennfahrer.php">
        <!-- ID is not needed, because its autogenerated by the database -->

        <!-- teamid textbox -->
        <div>
            <label for="new_teamid">teamid:</label>
            <input id="new_teamid" name="teamid" value="<?php echo $suchen["TEAMID"] ?>" type="number" maxlength="50">
        </div>
        <br>

        <!-- vorname textbox -->
        <div>
            <label for="new_vorname">vorname:</label>
            <input id="new_vorname" name="vorname" value="<?php echo $suchen["VORNAME"] ?>" type="text" maxlength="50">
        </div>
        <br>

        <!-- nachname textbox -->
        <div>
            <label for="new_nachname">nachname:</label>
            <input id="new_nachname" name="nachname"  value="<?php echo $suchen["NACHNAME"] ?>"type="text" maxlength="50">
        </div>
        <br>
        <!-- nationalitaet textbox -->
        <div>
            <label for="new_nationalitaet">nationalitaet:</label>
            <input id="new_nationalitaet" name="nationalitaet"  value="<?php echo $suchen["NATIONALITAET"] ?>"type="text" maxlength="50">
        </div>
        <br>
        <!-- gebdatum textbox -->
        <div>
            <label for="new_gebdatum">gebdatum(yyyy/mm/dd):</label>
            <input id="new_gebdatum" name="gebdatum"  value="<?php echo $suchen["GEBDATUM"] ?>"type="text" maxlength="50">
        </div>
        <br>
        <div>
            <button type="submit">
                Edit Rennfahrer
            </button>
        </div>
    </form>
</html>