<?php
require_once('header.php');
//include DatabaseHelper.php file
require_once('DatabaseHelper.php');

//instantiate DatabaseHelper class
$database = new DatabaseHelper();
//Grab variables from POST request

$autoid=$_GET['autoid'];
$suchen=$database->searchWagenByAutoId($autoid);

$suchen=array_shift($suchen);

if (count($suchen) == 0 ){
    echo "Error can't find Wagen with autoId: '{$autoid}'.";
    die();
}
?>

<h2>Edit Wagen: </h2>
<form method="get" action="addUpdateWagen.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- teamid textbox -->
    <div>
        <label for="new_teamid">teamid:</label>
        <input id="new_teamid" name="teamid" value="<?php echo $suchen["TEAMID"] ?>" type="number" maxlength="50">
    </div>
    <br>

    <!-- vorname textbox -->
    <div>
        <label for="new_vorname">vorname:</label>
        <input id="new_vorname" name="vorname" value="<?php echo $suchen["VORNAME"] ?>" type="text" maxlength="50">
    </div>
    <br>

    <!-- nachname textbox -->
    <div>
        <label for="new_nachname">nachname:</label>
        <input id="new_nachname" name="nachname"  value="<?php echo $suchen["NACHNAME"] ?>"type="text" maxlength="50">
    </div>
    <br>
    <!-- autoid textbox -->
    <div>
        <label for="new_autoid">AutoID:</label>
        <input id="new_autoid" name="autoid"  value="<?php echo $suchen["AUTOID"] ?>"type="number" maxlength="50">
    </div>
    <br>
    <!-- modell textbox -->
    <div>
        <label for="new_modell">Modell:</label>
        <input id="new_modell" name="modell"  value="<?php echo $suchen["MODELL"] ?>"type="text" maxlength="50">
    </div>
    <br>
    <!-- jahr textbox -->
    <div>
        <label for="new_jahr">Jahr:</label>
        <input id="new_jahr" name="jahr"  value="<?php echo $suchen["JAHR"] ?>"type="number" maxlength="50">
    </div>
    <br>
    <!-- leistung textbox -->
    <div>
        <label for="new_leistung">Leistung in kW:</label>
        <input id="new_leistung" name="leistung"  value="<?php echo $suchen["LEISTUNG"] ?>"type="number" maxlength="50">
    </div>
    <br>
    <!-- gewicht textbox -->
    <div>
        <label for="new_gewicht">Gewicht in kg:</label>
        <input id="new_gewicht" name="gewicht"  value="<?php echo $suchen["GEWICHT"] ?>"type="number" maxlength="50">
    </div>
    <br>
    <div>
        <button type="submit">
            Edit Wagen
        </button>
    </div>
</form>
</html>