create table team (
    teamId int primary key,
    teamName varchar(255) not null unique,
    gruendungsjahr int,
    check (gruendungsjahr <= 2021)
    );
    
create sequence teamId_seq start with 1;
    
create or replace trigger teamId_trg
    before insert on team
    for each row
    
    begin
        select teamId_seq.nextval
        into :new.teamId
        from dual;
end;
    
create table land(
    landname varchar(255) primary key,
    landkuerzel char(3)
    );
    
create table rennfahrerIn (
    teamId int references team(teamId),
    vorname varchar(255),
    nachname varchar(255),
    nationalitaet varchar(255),
    gebDatum date not null,
    primary key(teamId, vorname, nachname),
    foreign key(nationalitaet) references land(landname)
    );
    
create table hersteller(
    herstellername varchar(255) primary key,
    herstellerland varchar(255),
    gruendungsjahr int,
    foreign key(herstellerland) references land(landname)
    );
    
create table antrieb (
    antriebskuerzel char(3) primary key,
    antriebsbez varchar(75)
    );
    
create table modell(
    hersteller varchar(255),
    modellname varchar(255) primary key,
    antrieb char(3),
    foreign key(hersteller) references hersteller(herstellername),
    foreign key(antrieb) references antrieb(antriebskuerzel)
    );
    
create table wagen (
    teamId int,
    vorname varchar(255),
    nachname varchar(255),
    autoId int generated always as identity primary key,
    modell varchar(255),
    jahr int default 2022 check (jahr >= 1884 and jahr <= 2022),
    leistung int not null check (leistung >= 14),
    gewicht int not null check (gewicht >= 104),
    foreign key(teamId, vorname, nachname) references rennfahrerIn(teamId, vorname, nachname),
    foreign key(modell) references modell(modellname)
    );
    
create table kategorie(
    kategorie_abk varchar(10) primary key,
    kategoriename varchar(50)
    );
    
create table rennwagen (
    autoId int primary key,
    kategorie varchar(10),
    sponsor varchar(50),
    foreign key(kategorie) references kategorie(kategorie_abk),
    foreign key(autoId) references wagen(autoId)
    );

-- zeigt Rennwagen mit allen zugehoerigen Daten an
create view rennwagen_full as(
    select w.autoId, m.hersteller, w.modell, w.jahr, m.antrieb, w.leistung, w.gewicht, r.kategorie, r.sponsor from wagen w
        inner join modell m on m.modellname = w.modell
        inner join rennwagen r on r.autoId = w.autoId);
    
create table ansaugung (
    ans_kuerzel char(3) primary key check(ans_kuerzel in('SGM', 'T')),
    ans_bez varchar(10) check(ans_bez in('Saugmotor', 'Turbo'))
    );
    
create table strassenwagen (
    autoId int primary key,
    ansaugung char(3),
    farbe varchar(50) not null,
    foreign key(ansaugung) references ansaugung(ans_kuerzel),
    foreign key(autoId) references wagen(autoId)
    );
   
-- zeigt Strassenwagen mit allen zugehoerigen Daten an 
create view strassenwagen_full as(
    select w.autoId, m.hersteller, w.modell, w.jahr, m.antrieb, w.leistung, w.gewicht, s.ansaugung, s.farbe from wagen w
        inner join modell m on m.modellname = w.modell
        inner join strassenwagen s on s.autoId = w.autoId);
    
create table strecke(
    streckenname varchar(255) primary key,
    land varchar(255),
    streckenlaenge int not null,
    variante_von varchar(255) default null,
    foreign key(variante_von) references strecke(streckenname),
    foreign key(land) references land(landname)
    );
    
create table rennveranstaltung (
    rennverId int generated by default as identity primary key,
    rennverName varchar(255) not null,
    strecke varchar(255),
    datum date not null,
    foreign key(strecke) references strecke(streckenname)
    );
    
create table fahren(
    autoId int,
    rennverId int,
    runde int,
    rundenzeit int,
    primary key(autoId, rennverId, runde),
    foreign key(autoId) references wagen(autoId),
    foreign key(rennverId) references rennveranstaltung(rennverId)
    );

-- alle Bestzeiten pro Wagen fuer Rennveranstaltung 1
create view bestzeiten_1 as(
    select t.teamname, w.vorname, w.nachname, m.hersteller, m.modellname, min(f.rundenzeit) as bestzeit from fahren f
        inner join wagen w on w.autoid = f.autoid
        inner join rennfahrerin r on r.teamId = w.teamid
        inner join team t on t.teamid = r.teamid
        inner join modell m on m.modellname = w.modell
        where f.rennverid = 1
        group by t.teamname, w.vorname, w.nachname, m.hersteller, m.modellname having min(f.rundenzeit) < 800000);
        
-- alle Bestzeiten pro Wagen fuer Rennveranstaltung 1 wo die Zeit unter 9 min liegt
create view bestzeiten_1_q as(
    select t.teamname, w.vorname, w.nachname, m.hersteller, m.modellname, min(f.rundenzeit) as bestzeit from fahren f
        inner join wagen w on w.autoid = f.autoid
        inner join rennfahrerin r on r.teamId = w.teamid
        inner join team t on t.teamid = r.teamid
        inner join modell m on m.modellname = w.modell
        where f.rennverid = 1
        group by t.teamname, w.vorname, w.nachname, m.hersteller, m.modellname having min(f.rundenzeit) < 540000);

-- fuegt Rang ein fuer qualifizierte Bestzeiten
create view rankings_q as (
    select row_number() over(order by bestzeit) platz, a.* from bestzeiten_1_q a);

-- alle Rundenzeiten     
create view rundenzeiten_all as (
    select w.teamid, w.vorname, w.nachname,f.autoid, f.runde, f.rundenzeit from fahren f
        inner join wagen w on w.autoid = f.autoid
        where f.rennverid = 1);
        
-- fuegt Rang ein fuer Bestzeiten 
create view rankings as (
    select row_number() over(order by bestzeit) platz, a.* from bestzeiten_1 a);
    
-- erstellt view fuer qualifizierte Bestzeiten mit concat Monster, wo Rundenzeiten von ms zu mm:ss.fff richtig darstellt
create view rankings_q_time as (
    select platz, teamname, vorname, nachname, hersteller, modellname, concat(concat(concat(concat(concat(concat(concat(
        floor(bestzeit/60000),
        ':'), 
        floor(mod(bestzeit,60000)/10000)),
        floor(mod((mod(bestzeit, 60000)/1000), 10))),
        '.'),
        floor(mod((mod(bestzeit, 60000)), 1000)/100)), 
        floor(mod((mod((mod(bestzeit,60000)), 1000)/10),10))),
        mod((mod((mod(bestzeit,60000)), 10)),10)) as zeit from rankings_q);





