version: '3.8'
services:
  php-apache-environment:
    container_name: DB-Projekt-PHP
    image: ghcr.io/oracle/oraclelinux7-php:7.4-apache-oracledb
    volumes:
      - ./app/:/var/www/html/
    ports:
      - 8000:80